export const COMMENTS = [
            {
                id: 0,
                rating: 5,
                comment: 'Inquisitive insight, thorough report, and ended with a positive note!',
                author: 'Jade Do',
                date: '2018-10-24T17:57:28.556094Z',
                articleId: 0,
            },
            {
                id: 1,
                rating: 3,
                comment: 'I prefer a more entertainment-style form of information. Gonna head back to the home page for the movies.',
                author: 'Jade Do',
                date: '2018-10-26T17:57:28.556094Z',
                articleId: 0,
            },
            {
                id: 2,
                rating: 4,
                comment: 'A few institutions have closed down their Confucius Institute, however, some, due to financial and monetary benefits, are reluctant to do so.',
                author: 'Jade Do',
                date: '2018-10-24T17:57:28.556094Z',
                articleId: 1,
            },
            {
                id: 3,
                rating: 5,
                comment: 'In the name of Confucius, I beg the CCP please don\'t mar the name of Confucius',
                author: 'Jade Do',
                date: '2018-10-24T17:57:28.556094Z',
                articleId: 1,
            },
            {
                id: 4,
                rating: 3,
                comment: 'CSSA is somewhat a physical entity of the consulate of China in the U.S.. Is this something that the Land of Freedom shoult tolerate?',
                author: 'Jade Do',
                date: '2018-10-26T17:17:28.556094Z',
                articleId: 2,
            },
            {
                id: 5,
                rating: 4,
                comment: 'There is a CSSA in University of Miami.',
                author: 'Jade Do',
                date: '2018-10-26T17:00:00.556094Z',
                articleId: 2,
            },
            {
                id: 6,
                rating: 5,
                comment: 'History and politics classes teach students what wrongful deeds Communism commits. The is the first book to ever answer the question, what is the nature of Communism.',
                author: 'Jade Do',
                date: '2018-25-24T19:57:28.556094Z',
                articleId: 3,
            },
            {
                id: 7,
                rating: 4,
                comment: 'Another riveting book examining the nature, the objective and the goal of Communism. How do we escape from it?',
                author: 'Jade Do',
                date: '2018-10-25T19:37:18.556394Z',
                articleId: 4,
            },
            {
                id: 8,
                rating: 5,
                comment: 'Disheartening. Brutal.',
                author: 'Jade Do',
                date: '2018-10-25T20:37:18.556394Z',
                articleId: 5,
            },
]